#!/usr/bin/env bash
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=1 --max-zoom=1 --min-x=1 --max-x=1 --min-y=1 --max-y=1
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=2 --max-zoom=2 --min-x=2 --max-x=2 --min-y=2 --max-y=2
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=3 --max-zoom=3 --min-x=4 --max-x=4 --min-y=5 --max-y=5
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=4 --max-zoom=4 --min-x=8 --max-x=8 --min-y=10 --max-y=10
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=5 --max-zoom=5 --min-x=16 --max-x=16 --min-y=20 --max-y=20
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=6 --max-zoom=6 --min-x=33 --max-x=33 --min-y=41 --max-y=41
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=7 --max-zoom=7 --min-x=66 --max-x=66 --min-y=83 --max-y=83
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=8 --max-zoom=8 --min-x=132 --max-x=133 --min-y=166 --max-y=166
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=9 --max-zoom=9 --min-x=265 --max-x=266 --min-y=332 --max-y=333
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=10 --max-zoom=10 --min-x=531 --max-x=532 --min-y=665 --max-y=667
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=11 --max-zoom=11 --min-x=1063 --max-x=1065 --min-y=1331 --max-y=1335
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=12 --max-zoom=12 --min-x=2127 --max-x=2130 --min-y=2663 --max-y=2670
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=13 --max-zoom=13 --min-x=4255 --max-x=4260 --min-y=5326 --max-y=5340
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=14 --max-zoom=14 --min-x=8511 --max-x=8520 --min-y=10652 --max-y=10681
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=15 --max-zoom=15 --min-x=17023 --max-x=17040 --min-y=21305 --max-y=21363
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=16 --max-zoom=16 --min-x=34046 --max-x=34080 --min-y=42611 --max-y=42727
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=17 --max-zoom=17 --min-x=68092 --max-x=68161 --min-y=85223 --max-y=85455
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=18 --max-zoom=18 --min-x=136185 --max-x=136322 --min-y=170447 --max-y=170910
