#!/usr/bin/env bash
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=1 --max-zoom=1 --min-x=1 --max-x=1 --min-y=0 --max-y=0
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=2 --max-zoom=2 --min-x=2 --max-x=2 --min-y=1 --max-y=1
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=3 --max-zoom=3 --min-x=4 --max-x=4 --min-y=2 --max-y=2
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=4 --max-zoom=4 --min-x=8 --max-x=8 --min-y=5 --max-y=5
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=5 --max-zoom=5 --min-x=16 --max-x=16 --min-y=10 --max-y=10
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=6 --max-zoom=6 --min-x=33 --max-x=33 --min-y=21 --max-y=21
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=7 --max-zoom=7 --min-x=66 --max-x=66 --min-y=42 --max-y=43
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=8 --max-zoom=8 --min-x=132 --max-x=133 --min-y=85 --max-y=86
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=9 --max-zoom=9 --min-x=265 --max-x=266 --min-y=171 --max-y=172
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=10 --max-zoom=10 --min-x=531 --max-x=532 --min-y=343 --max-y=344
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=11 --max-zoom=11 --min-x=1063 --max-x=1065 --min-y=687 --max-y=688
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=12 --max-zoom=12 --min-x=2127 --max-x=2130 --min-y=1375 --max-y=1377
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=13 --max-zoom=13 --min-x=4255 --max-x=4260 --min-y=2750 --max-y=2755
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=14 --max-zoom=14 --min-x=8511 --max-x=8520 --min-y=5501 --max-y=5511
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=15 --max-zoom=15 --min-x=17023 --max-x=17040 --min-y=11002 --max-y=11022
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=16 --max-zoom=16 --min-x=34046 --max-x=34080 --min-y=22005 --max-y=22045
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=17 --max-zoom=17 --min-x=68092 --max-x=68161 --min-y=44010 --max-y=44091
render_list --all ---socket=/run/renderd/renderd.sock --force --map= osm --num-threads= 4 --min-zoom=18 --max-zoom=18 --min-x=136185 --max-x=136322 --min-y=88020 --max-y=88183
